
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`include "fixed.sv"
`default_nettype none
import global_enums::*;

module autotune (

    //////////// ADC //////////
    output ADC_CONVST,
    output ADC_DIN,
    input  ADC_DOUT,
    output ADC_SCLK,

    //////////// Audio //////////
    input  AUD_ADCDAT,
    inout  AUD_ADCLRCK,
    inout  AUD_BCLK,
    output AUD_DACDAT,
    inout  AUD_DACLRCK,
    output AUD_XCK,

    //////////// CLOCK //////////
    input CLOCK2_50,
    input CLOCK3_50,
    input CLOCK4_50,
    input CLOCK_50,

    //////////// SDRAM //////////
    output [12:0] DRAM_ADDR,
    output [ 1:0] DRAM_BA,
    output        DRAM_CAS_N,
    output        DRAM_CKE,
    output        DRAM_CLK,
    output        DRAM_CS_N,
    inout  [15:0] DRAM_DQ,
    output        DRAM_LDQM,
    output        DRAM_RAS_N,
    output        DRAM_UDQM,
    output        DRAM_WE_N,

    //////////// I2C for Audio and Video-In //////////
    output FPGA_I2C_SCLK,
    inout  FPGA_I2C_SDAT,

    //////////// SEG7 //////////
    output [6:0] HEX0,
    output [6:0] HEX1,
    output [6:0] HEX2,
    output [6:0] HEX3,
    output [6:0] HEX4,
    output [6:0] HEX5,

    //////////// IR //////////
    input  IRDA_RXD,
    output IRDA_TXD,

    //////////// KEY //////////
    input [3:0] KEY,

    //////////// LED //////////
    output [9:0] LEDR,

    //////////// PS2 //////////
    inout PS2_CLK,
    inout PS2_CLK2,
    inout PS2_DAT,
    inout PS2_DAT2,

    //////////// SW //////////
    input [9:0] SW,

    inout [35:0] GPIO,

    //////////// Video-In //////////
    input        TD_CLK27,
    input  [7:0] TD_DATA,
    input        TD_HS,
    output       TD_RESET_N,
    input        TD_VS,

    //////////// VGA //////////
    output       VGA_BLANK_N,
    output [7:0] VGA_B,
    output       VGA_CLK,
    output [7:0] VGA_G,
    output       VGA_HS,
    output [7:0] VGA_R,
    output       VGA_SYNC_N,
    output       VGA_VS
);
  wire rst = ~KEY[0];

  // Safe defaults for unused interfaces (codec bypass test only)
  assign ADC_CONVST  = 1'b0;
  assign ADC_DIN     = 1'b0;
  assign ADC_SCLK    = 1'b0;
  //assign AUD_DACDAT  = 1'b0;
  //assign AUD_XCK     = 1'b0;
  assign TD_RESET_N  = 1'b1;

  // Leave shared audio clocks/LRCK as Hi-Z (not used for analogue bypass)
  //assign AUD_ADCLRCK = 1'bz;
  //assign AUD_BCLK    = 1'bz;
  //assign AUD_DACLRCK = 1'bz;

  assign IRDA_TXD    = 1'b1;

  assign DRAM_ADDR   = '0;
  assign DRAM_BA     = '0;
  assign DRAM_CAS_N  = 1'b1;
  assign DRAM_CKE    = 1'b0;
  assign DRAM_CLK    = 1'b0;
  assign DRAM_CS_N   = 1'b1;
  assign DRAM_LDQM   = 1'b0;
  assign DRAM_RAS_N  = 1'b1;
  assign DRAM_UDQM   = 1'b0;
  assign DRAM_WE_N   = 1'b1;

  assign VGA_BLANK_N = 1'b1;
  assign VGA_B       = '0;
  assign VGA_CLK     = 1'b0;
  assign VGA_G       = '0;
  assign VGA_HS      = 1'b0;
  assign VGA_R       = '0;
  assign VGA_SYNC_N  = 1'b1;
  assign VGA_VS      = 1'b0;
  
  logic lrck;

  assign AUD_ADCLRCK = lrck;
  assign AUD_DACLRCK = lrck;

  top #(
    .WINDOW_SIZE(1024)
  ) iTOP ( 
    .clk(CLOCK_50),
    .rst(rst),
    .i_aud_adcdat(AUD_ADCDAT),
    .o_aud_dacdat(AUD_DACDAT),
    .o_aud_bclk(AUD_BCLK),
    .o_aud_lrck(lrck),
    .o_aud_xck(AUD_XCK),
    .o_fpga_i2c_sclk(FPGA_I2C_SCLK),
    .o_fpga_i2c_sdat(FPGA_I2C_SDAT),
    .i_rxd(GPIO[5]),
    .o_txd(GPIO[4]),
    .i_mech(SW[0]),
    .SW(SW),
    .LEDR(LEDR),
    .HEX0(HEX0),
    .HEX1(HEX1),
    .HEX2(HEX2),
    .HEX3(HEX3),
    .HEX4(HEX4),
    .HEX5(HEX5)
  );

endmodule
