`timescale 1ns / 1ps

`include "fixed.sv"

// Time-multiplexed bandpass filterbank.
//
// BANKS  = number of coefficient sets / independent filters.
//
// On each input sample strobe (i_valid), the module latches i_data and then
// spends BANKS clock cycles updating all BANKS filters for that
// sample. When finished, it pulses o_valid for 1 cycle.
//
// Coefficients are specified as pre-computed Q11.16 fixed_t parameter tables.
// Use py/gen_bandpass_coeffs.py to convert from floating-point.
module bandpass_sosfilt_bank #(
    parameter int BANKS = 1,
    parameter int BBITS = $clog2(BANKS)
) (
    input  wire                  clk,
    input  wire                  rst,
    input  fixed_t               i_data,
    input  wire                  i_valid,
    input  wire                  i_asym_follow,
    input  wire    [BBITS - 1:0] i_bank_start,
    input  wire    [BBITS - 1:0] i_bank_end,
    output fnorm_t               o_data       [BANKS],
    output wire                  o_valid
);
  localparam int BANKW = (BANKS <= 1) ? 1 : $clog2(BANKS);

  // Coefficient ROMs (loaded from mem files generated by py/gen_bandpass_coeffs.py)
  logic [31:0] B0[BANKS], B1[BANKS], B2[BANKS], A1[BANKS], A2[BANKS];
  logic [31:0] C0[BANKS], C1[BANKS], C2[BANKS], D1[BANKS], D2[BANKS];
  initial begin
    $readmemh("vocoder_bp_s0_b0.mem", B0);
    $readmemh("vocoder_bp_s0_b1.mem", B1);
    $readmemh("vocoder_bp_s0_b2.mem", B2);
    $readmemh("vocoder_bp_s0_a1.mem", A1);
    $readmemh("vocoder_bp_s0_a2.mem", A2);
    $readmemh("vocoder_bp_s1_b0.mem", C0);
    $readmemh("vocoder_bp_s1_b1.mem", C1);
    $readmemh("vocoder_bp_s1_b2.mem", C2);
    $readmemh("vocoder_bp_s1_a1.mem", D1);
    $readmemh("vocoder_bp_s1_a2.mem", D2);
  end

  // (Optional) asymmetric envelope follower(s) are applied AFTER the bandpass
  // filter outputs, not on the raw input.

  // ----------------------------------------------------------------
  // Control: one-bank-at-a-time sequencing
  // ----------------------------------------------------------------
  typedef enum logic [1:0] {
    WAITING,
    CALCULATING,
    DONE
  } state_t;
  state_t             state;

  fnorm_t             x_hold;
  logic   [BANKW-1:0] bank_idx;
  logic               inflight;

  // Selected coefficients for current bank
  fnorm_t i_b0, i_b1, i_b2, i_a1, i_a2;
  fnorm_t i_c0, i_c1, i_c2, i_d1, i_d2;

  always_comb begin
    i_b0 = fnorm_t'(B0[bank_idx][26:0]);
    i_b1 = fnorm_t'(B1[bank_idx][26:0]);
    i_b2 = fnorm_t'(B2[bank_idx][26:0]);
    i_a1 = fnorm_t'(A1[bank_idx][26:0]);
    i_a2 = fnorm_t'(A2[bank_idx][26:0]);

    i_c0 = fnorm_t'(C0[bank_idx][26:0]);
    i_c1 = fnorm_t'(C1[bank_idx][26:0]);
    i_c2 = fnorm_t'(C2[bank_idx][26:0]);
    i_d1 = fnorm_t'(D1[bank_idx][26:0]);
    i_d2 = fnorm_t'(D2[bank_idx][26:0]);
  end

  // ----------------------------------------------------------------
  // Single shared filter instance (internal state is banked by i_bank)
  // ----------------------------------------------------------------
  logic   filt_i_valid;
  fnorm_t filt_o_data;
  logic   filt_o_valid;

  bandpass_sosfilt #(
      .BANKS (BANKS),
      .BANK_W(BANKW)
  ) u_bandpass_sosfilt (
      .clk    (clk),
      .rst    (rst),
      .i_data (x_hold),
      .i_valid(filt_i_valid),
      .i_bank (bank_idx),
      .i_b0   (i_b0),
      .i_b1   (i_b1),
      .i_b2   (i_b2),
      .i_a1   (i_a1),
      .i_a2   (i_a2),
      .i_c0   (i_c0),
      .i_c1   (i_c1),
      .i_c2   (i_c2),
      .i_d1   (i_d1),
      .i_d2   (i_d2),
      .o_data (filt_o_data),
      .o_valid(filt_o_valid)
  );

  // ----------------------------------------------------------------
  // Optional post-processing: time-multiplexed asymmetric follower
  // (single datapath, banked internal state selected by i_bank)
  // ----------------------------------------------------------------
  fnorm_t post_o_data;
  wire    post_o_valid;

  fnorm_t asym_o_data;
  wire    asym_o_valid;

  asym_follow #(
      .BANKS (BANKS),
      .BANK_W(BANKW)
  ) u_asym_follow (
      .clk    (clk),
      .rst    (rst),
      .i_data (fnorm_abs(filt_o_data)),
      .i_valid(filt_o_valid),
      .i_bank (bank_idx),
      .o_data (asym_o_data),
      .o_valid(asym_o_valid)
  );

  always_comb begin
    if (i_asym_follow) begin
      post_o_data  = asym_o_data;
      post_o_valid = asym_o_valid;
    end else begin
      post_o_data  = filt_o_data;
      post_o_valid = filt_o_valid;
    end
  end

  // ----------------------------------------------------------------
  // FSM: WAITING -> CALCULATING (iterate banks) -> DONE (1-cycle pulse)
  // Assumes i_valid only asserted when idle (WAITING).
  // ----------------------------------------------------------------
  logic o_valid_r;
  assign o_valid = o_valid_r;

  integer ob;
  always_ff @(posedge clk) begin
    if (rst) begin
      state        <= WAITING;
      o_valid_r    <= 1'b0;
      filt_i_valid <= 1'b0;
      x_hold       <= '0;
      bank_idx     <= '0;
      inflight     <= 1'b0;
      for (ob = 0; ob < BANKS; ob++) begin
        o_data[ob] <= '0;
      end
    end else begin
      // defaults (single-cycle pulses)
      o_valid_r    <= 1'b0;
      filt_i_valid <= 1'b0;

      case (state)
        WAITING: begin
          inflight <= 1'b0;
          if (i_valid) begin
            x_hold   <= fnorm_t'(i_data >> 10);
            bank_idx <= i_bank_start;
            state    <= CALCULATING;
          end
        end

        CALCULATING: begin
          // Kick the current bank once, then wait for its output.
          if (!inflight) begin
            filt_i_valid <= 1'b1;
            inflight     <= 1'b1;
          end else if (post_o_valid) begin
            o_data[bank_idx] <= post_o_data;
            inflight         <= 1'b0;

            if (bank_idx == i_bank_end) begin
              state <= DONE;
            end else begin
              bank_idx <= bank_idx + 1;
            end
          end
        end

        DONE: begin
          o_valid_r <= 1'b1;
          state     <= WAITING;
        end

        default: state <= WAITING;
      endcase
    end
  end

endmodule
