// Markov-chain harmony generator. Produces two pitch-shift ratios for the
// downstream PSOLA harmony channels based on:
//   - the current melody MIDI note (midi_in, with note_valid strobe)
//   - a runtime tonic (4-bit, 0=C..11=B)
//   - a Markov chord progression that advances on internal chord_tick (rising
//     edge of midi_in change, qualified by note_valid)
//
// Output `harm{1,2}_ratio` are *Q11.16 reciprocal* frequency ratios — drop-in
// scale factors for PSOLA's i_advance. Compute final per-harmony advance as
//     fixed_mul(eff_pitch_factor, harmN_ratio).
// This differs from the original spec's Q4.12 forward-ratio convention; the
// reciprocal form avoids a runtime divide at integration.
//
// ROMs generated by py/build_harmony_roms.py.

`include "fixed.sv"

module harmony_gen (
    input  logic        clk,
    input  logic        rst,

    input  logic [3:0]  tonic,        // 0=C..11=B (12..15 clamped to 0)
    input  logic [6:0]  midi_in,
    input  logic        note_valid,   // single-cycle strobe when midi_in updates

    output fixed_t      harm1_ratio,  // Q11.16 reciprocal, multiply with eff_pitch_factor
    output fixed_t      harm2_ratio,
    output logic        ratios_valid,
    output logic [2:0]  o_chord_state,  // debug
    output logic        o_in_scale       // debug
);

  // ----------------------------------------------------------------
  // ROMs
  // ----------------------------------------------------------------
  logic [3:0] scale_rom    [12];
  logic [7:0] trans_rom    [64];
  logic [15:0] voic_rom    [64];
  logic [31:0] ratio_rom   [33];

  initial begin
    $readmemh("scale_degree_rom.mem", scale_rom);
    $readmemh("transition_rom.mem",   trans_rom);
    $readmemh("voicing_rom.mem",      voic_rom);
    $readmemh("harmony_ratio_rom.mem", ratio_rom);
  end

  // ----------------------------------------------------------------
  // Tonic sanitization
  // ----------------------------------------------------------------
  logic [3:0] tonic_eff;
  assign tonic_eff = (tonic >= 4'd12) ? 4'd0 : tonic;

  // ----------------------------------------------------------------
  // pitch_class = (midi_in - tonic) mod 12
  // Pre-bias by 132 (=11*12) so the unsigned subtract never underflows.
  // ----------------------------------------------------------------
  logic [8:0] pc_adj;
  assign pc_adj = {2'b00, midi_in} + 9'd132 - {5'b00000, tonic_eff};

  logic [8:0] pc_red;
  always_comb begin
    pc_red = pc_adj;
    if (pc_red >= 9'd192) pc_red -= 9'd192; // 16*12
    if (pc_red >= 9'd96)  pc_red -= 9'd96;  // 8*12
    if (pc_red >= 9'd48)  pc_red -= 9'd48;  // 4*12
    if (pc_red >= 9'd24)  pc_red -= 9'd24;  // 2*12
    if (pc_red >= 9'd12)  pc_red -= 9'd12;
  end
  logic [3:0] pitch_class;
  assign pitch_class = pc_red[3:0];

  // ----------------------------------------------------------------
  // Scale-degree ROM lookup
  // ----------------------------------------------------------------
  logic [3:0] scale_word;
  logic [2:0] scale_degree;
  logic       in_scale;
  assign scale_word   = scale_rom[pitch_class];
  assign scale_degree = scale_word[2:0];
  assign in_scale     = scale_word[3];
  assign o_in_scale   = in_scale;

  // ----------------------------------------------------------------
  // chord_tick: rising edge of midi_in change, qualified by note_valid.
  // ----------------------------------------------------------------
  logic [6:0] prev_midi;
  logic       chord_tick;
  always_ff @(posedge clk) begin
    if (rst) prev_midi <= 7'd0;
    else if (note_valid) prev_midi <= midi_in;
  end
  assign chord_tick = note_valid & (midi_in != prev_midi);

  // ----------------------------------------------------------------
  // 16-bit Galois LFSR — taps {15,14,12,3} ⇒ x^16 + x^15 + x^13 + x^4 + 1
  // (a known maximum-length poly). Advances one step per chord_tick.
  // ----------------------------------------------------------------
  logic [15:0] lfsr;
  always_ff @(posedge clk) begin
    if (rst) lfsr <= 16'hACE1;
    else if (chord_tick)
      lfsr <= {lfsr[14:0], 1'b0} ^ ({16{lfsr[15]}} & 16'hB400);
  end
  wire [7:0] r = lfsr[7:0];

  // ----------------------------------------------------------------
  // Markov FSM
  // ----------------------------------------------------------------
  logic [2:0] chord_state;

  // Read the 7 CDF entries for the current row in parallel.
  logic [7:0] cdf [7];
  always_comb begin
    for (int i = 0; i < 7; i++) begin
      cdf[i] = trans_rom[{chord_state, 3'(i)}];
    end
  end

  logic [2:0] next_chord;
  always_comb begin
    if      (cdf[0] > r) next_chord = 3'd1;
    else if (cdf[1] > r) next_chord = 3'd2;
    else if (cdf[2] > r) next_chord = 3'd3;
    else if (cdf[3] > r) next_chord = 3'd4;
    else if (cdf[4] > r) next_chord = 3'd5;
    else if (cdf[5] > r) next_chord = 3'd6;
    else                  next_chord = 3'd7;
  end

  always_ff @(posedge clk) begin
    if (rst) chord_state <= 3'd1;             // start on I
    else if (chord_tick) chord_state <= next_chord;
  end
  assign o_chord_state = chord_state;

  // ----------------------------------------------------------------
  // Voicing ROM lookup (combinational, current chord & scale_degree)
  // ----------------------------------------------------------------
  logic [15:0] voic_word;
  assign voic_word = voic_rom[{chord_state, scale_degree}];
  logic signed [7:0] harm1_semi;
  logic signed [7:0] harm2_semi;
  assign harm1_semi = $signed(voic_word[15:8]);
  assign harm2_semi = $signed(voic_word[7:0]);

  // ----------------------------------------------------------------
  // Ratio ROM — addr = signed_semi + 16. Clamp out-of-range entries.
  // ----------------------------------------------------------------
  function automatic logic [5:0] ratio_addr(input logic signed [7:0] semi);
    if (semi < -16)      ratio_addr = 6'd0;
    else if (semi > 16)  ratio_addr = 6'd32;
    else                 ratio_addr = 6'(semi + 16);
  endfunction

  logic [31:0] r1_word, r2_word;
  assign r1_word = ratio_rom[ratio_addr(harm1_semi)];
  assign r2_word = ratio_rom[ratio_addr(harm2_semi)];

  // ----------------------------------------------------------------
  // Output registers — pulse ratios_valid one cycle after note_valid.
  // (also updates after chord_tick, which co-fires with note_valid by
  // construction.)
  // ----------------------------------------------------------------
  fixed_t harm1_ratio_r, harm2_ratio_r;
  logic   ratios_valid_r;

  always_ff @(posedge clk) begin
    if (rst) begin
      harm1_ratio_r  <= '0;
      harm2_ratio_r  <= '0;
      ratios_valid_r <= 1'b0;
    end else begin
      ratios_valid_r <= note_valid;
      if (note_valid) begin
        harm1_ratio_r <= fixed_t'(r1_word[26:0]);
        harm2_ratio_r <= fixed_t'(r2_word[26:0]);
      end
    end
  end

  assign harm1_ratio  = harm1_ratio_r;
  assign harm2_ratio  = harm2_ratio_r;
  assign ratios_valid = ratios_valid_r;

endmodule
