// Inverse of midi_lag_lut: maps a 10-bit pitch_period lag (samples @48 kHz)
// to the nearest MIDI note number, clamped to [0, 127]. Generated by
// py/build_harmony_roms.py.
module lag_to_midi_lut (
    input  wire [9:0] i_lag,
    output wire [6:0] o_midi
);
  logic [7:0] lut[1024];
  initial $readmemh("lag_to_midi.mem", lut);

  assign o_midi = lut[i_lag][6:0];
endmodule
