
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module midi(

 //////////// CLOCK //////////
    input               CLOCK_50,
    input               CLOCK2_50,
    input               CLOCK3_50,
    input               CLOCK4_50,

 //////////// SEG7 //////////
    output logic      [6:0]  HEX0,
    output logic      [6:0]  HEX1,
    output logic      [6:0]  HEX2,
    output logic      [6:0]  HEX3,
    output logic      [6:0]  HEX4,
    output logic      [6:0]  HEX5,

//////////// KEY //////////
    input        [3:0]  KEY,

 //////////// LED //////////
    output		   [9:0]		LEDR,

 //////////// SW //////////
    input        [9:0]  SW,

 //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
    inout       [35:0]  GPIO
);

wire rxd;
wire [1:0] br_cfg;

// press button[0] to generate a low active reset signal
wire rst = ~KEY[0];

// GPIO[5] as RX input
assign rxd = GPIO[5];

// MIDI Signals
wire note_on_trigger;
wire [6:0] note_number;
wire [6:0] velocity;

// Instantiate midi receiver here
midi_receiver midi_receiver0(
    .clk(CLOCK_50),
    .rst(rst),
    .midi_rx(rxd),
    .note_on_trigger(note_on_trigger),
    .note_number(note_number),
    .velocity(velocity)
);

// Frequency LUT and Display Logic
wire [23:0] frequency_x1000;
wire [31:0] bcd_freq;

// // LUT to get frequency * 1000 from note number
// midi_freq_lut lut0 (
//     .note(note_number),
//     .frequency_x1000(frequency_x1000)
// );

// // Convert binary frequency to BCD for display
// bin_to_bcd bcd0 (
//     .bin(frequency_x1000),
//     .bcd(bcd_freq)
// );

reg [23:0] display_bcd;
always @(*) begin
    if (SW[0]) begin
        // Show upper digits (digits 2-7) for high frequencies
        display_bcd = bcd_freq[31:8]; 
    end else begin
        // Show lower digits (digits 0-5) normally
        display_bcd = bcd_freq[23:0];
    end
end

function [6:0] seven_seg_decode;
    input [3:0] val;
    begin
        case (val)
            4'h0: seven_seg_decode = 7'b1000000;
            4'h1: seven_seg_decode = 7'b1111001;
            4'h2: seven_seg_decode = 7'b0100100;
            4'h3: seven_seg_decode = 7'b0110000;
            4'h4: seven_seg_decode = 7'b0011001;
            4'h5: seven_seg_decode = 7'b0010010;
            4'h6: seven_seg_decode = 7'b0000010;
            4'h7: seven_seg_decode = 7'b1111000;
            4'h8: seven_seg_decode = 7'b0000000;
            4'h9: seven_seg_decode = 7'b0011000;
            4'hA: seven_seg_decode = 7'b0001000;
            4'hB: seven_seg_decode = 7'b0000011;
            4'hC: seven_seg_decode = 7'b1000110;
            4'hD: seven_seg_decode = 7'b0100001;
            4'hE: seven_seg_decode = 7'b0000110;
            4'hF: seven_seg_decode = 7'b0001110;
            default: seven_seg_decode = 7'b1111111;
        endcase
    end
endfunction

always @(*) begin
    // HEX0 = seven_seg_decode(frequency_x1000[3:0]);
    // HEX1 = seven_seg_decode(frequency_x1000[7:4]);
    // HEX2 = seven_seg_decode(frequency_x1000[11:8]);
    // HEX3 = seven_seg_decode(frequency_x1000[15:12]);
    // HEX4 = seven_seg_decode(frequency_x1000[19:16]);
    // HEX5 = seven_seg_decode(frequency_x1000[23:20]);
    HEX0 = seven_seg_decode(note_number[3:0]);
    HEX1 = seven_seg_decode(note_number[6:4]);
end

endmodule
