
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module midi(

 //////////// CLOCK //////////
    input               CLOCK_50,
    input               CLOCK2_50,
    input               CLOCK3_50,
    input               CLOCK4_50,

 //////////// SEG7 //////////
    output logic      [6:0]  HEX0,
    output logic      [6:0]  HEX1,
    output logic      [6:0]  HEX2,
    output logic      [6:0]  HEX3,
    output logic      [6:0]  HEX4,
    output logic      [6:0]  HEX5,

//////////// KEY //////////
    input        [3:0]  KEY,

 //////////// LED //////////
    output		   [9:0]		LEDR,

 //////////// SW //////////
    input        [9:0]  SW,

 //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
    inout       [35:0]  GPIO
);

wire rxd;
wire [1:0] br_cfg;

// press button[0] to generate a low active reset signal
wire rst = ~KEY[0];

// GPIO[5] as RX input
assign rxd = GPIO[5];

// MIDI Signals
wire note_on_trigger;
wire [6:0] note_number;
wire [6:0] velocity;

// Instantiate midi receiver here
midi_receiver midi_receiver0(
    .clk(CLOCK_50),
    .rst(rst),
    .midi_rx(rxd),
    .note_on_trigger(note_on_trigger),
    .note_number(note_number),
    .velocity(velocity)
);

// Frequency LUT and Display Logic
wire [26:0] frequency;
wire [23:0] bcd_freq;

// LUT to get Q11.16 frequency from note number
midi_freq_lut lut0 (
    .note(note_number),
    .frequency(frequency)
);

// Convert Q11.16 frequency to 6 BCD decimal digits for display
bin_to_bcd bcd0 (
    .freq_q1116(frequency),
    .bcd(bcd_freq)
);

function [6:0] seven_seg_decode;
    input [3:0] val;
    begin
        case (val)
            4'h0: seven_seg_decode = 7'b1000000;
            4'h1: seven_seg_decode = 7'b1111001;
            4'h2: seven_seg_decode = 7'b0100100;
            4'h3: seven_seg_decode = 7'b0110000;
            4'h4: seven_seg_decode = 7'b0011001;
            4'h5: seven_seg_decode = 7'b0010010;
            4'h6: seven_seg_decode = 7'b0000010;
            4'h7: seven_seg_decode = 7'b1111000;
            4'h8: seven_seg_decode = 7'b0000000;
            4'h9: seven_seg_decode = 7'b0011000;
            4'hA: seven_seg_decode = 7'b0001000;
            4'hB: seven_seg_decode = 7'b0000011;
            4'hC: seven_seg_decode = 7'b1000110;
            4'hD: seven_seg_decode = 7'b0100001;
            4'hE: seven_seg_decode = 7'b0000110;
            4'hF: seven_seg_decode = 7'b0001110;
            default: seven_seg_decode = 7'b1111111;
        endcase
    end
endfunction

always @(*) begin
    HEX0 = seven_seg_decode(bcd_freq[3:0]);    // hundredths Hz
    HEX1 = seven_seg_decode(bcd_freq[7:4]);    // tenths Hz
    HEX2 = seven_seg_decode(bcd_freq[11:8]);   // ones Hz
    HEX3 = seven_seg_decode(bcd_freq[15:12]);  // tens Hz
    HEX4 = seven_seg_decode(bcd_freq[19:16]);  // hundreds Hz
    HEX5 = seven_seg_decode(bcd_freq[23:20]);  // thousands Hz
end

endmodule
